// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqdmacbnxdoywrtuaxxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZG1hY2JueGRveXdydHVheHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzgzNzYsImV4cCI6MjA1ODkxNDM3Nn0._cd5DKEDk0F4UUKwD1HM-aXe5jO-JlGKtrKGisZRbbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);